=== hrpunio/Z-MISC/Erasmus/2018/2018/memo.dtd
<!-- DTD for simple office memoranda -->
<!-- Elements -->
<!ELEMENT memo  (to, from, body, close?)   >
<!ELEMENT to    (#PCDATA) >
<!ELEMENT from  (#PCDATA) >
<!ELEMENT body  (p*) >
<!ELEMENT p     (#PCDATA | q | pref )* >
<!ELEMENT q     (#PCDATA) >
<!ELEMENT pref  EMPTY >
<!ELEMENT close (#PCDATA) >
<!-- Attributes  -->
<!-- ELEMENTS NAME VALUE DEFAULT -->
<!ATTLIST p    id      ID #IMPLIED  >
<!ATTLIST pref refid   IDREF #REQUIRED >
<!ATTLIST memo status (confiden | public) "public" 
               date    CDATA #IMPLIED >

=== hrpunio/Z-MISC/Erasmus/2018/2018/snowden2napoleon.xml
<?xml version='1.0' encoding='utf-8' ?>
<!DOCTYPE memo SYSTEM "./memo.dtd">
<memo >
<to>Comrade Napoleon</to>
<from>Snowball</from>
<body>
<p>
If pro is the opposite of con, and progress 
is moving forward, what is congress?
See paragraph <pref refid='congr.def'/> for
an answer </p>
<!-- ... omitted p elements -->
<p id='congr.def'>According to Professor Squealer 
<q>Con In Latin means together 
and Gradi means to walk.  Congradi literally 
means meeting. This became congressus 
and then Congress in English.</q> 
BTW recontre is the verb to meet in French...
</p>
</body>
<close>Comrade Snowball</close>
</memo>
